### ISSUE TITLE
Option to not include the Customer information sensor

### ISSUE THREAD

**Issue by sepodele** [toringer/home-assistant-sbanken#14]
Can you either remove the customer information sensor or let it be possible to not include it on setup? I don't like having all that personal information in HA. Simply disabling it won't delete the data once it's set up.

**Comment by sepodele** [comment]
Thanks. Personally I'd prefer it to be removed completely. I can't see it adds anything of value. I already know my name and other personal information. ;)

**Comment by sepodele** [comment]
Any progress? :)

**Comment by toringer** [comment]
Removed in release 2.2.0 :thumbsup:
