### ISSUE TITLE
Integration will stop working in 2023.3

### ISSUE THREAD

**Issue by sepodele** [toringer/home-assistant-sbanken#15]
I got this warning in logs: "Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for sbanken using this method at custom_components/sbanken/__init__.py, line 19: hass.config_entries.async_setup_platforms(entry, PLATFORMS)"

**Comment by toringer** [comment]
Thanks for letting me know. Fixed in v2.2.1
